# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/windows" = {
      device = "/dev/disk/by-uuid/84C21617C2160E54";
      fsType = "ntfs";
      options = ["nofail"];
    };
    "/" = {
      device = "/dev/disk/by-uuid/3b1ab498-b937-46b2-b935-cfcc9ea43364";
      fsType = "btrfs";
      options = ["subvol=root" "compress=zstd"];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/3b1ab498-b937-46b2-b935-cfcc9ea43364";
      fsType = "btrfs";
      options = ["subvol=home" "compress=zstd"];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/3b1ab498-b937-46b2-b935-cfcc9ea43364";
      fsType = "btrfs";
      options = ["subvol=nix" "noatime" "compress=zstd"];
    };
    "/games" = {
      device = "/dev/disk/by-uuid/3b1ab498-b937-46b2-b935-cfcc9ea43364";
      fsType = "btrfs";
      options = ["subvol=games" "compress=zstd"];
    };
    "/documents" = {
      device = "/dev/disk/by-uuid/3b1ab498-b937-46b2-b935-cfcc9ea43364";
      fsType = "btrfs";
      options = ["subvol=documents" "compress=zstd"];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/525E-E4E6";
      fsType = "vfat";
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
