# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a0da699c-99b7-4ea5-8757-35e1ca611c2d";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd"];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a0da699c-99b7-4ea5-8757-35e1ca611c2d";
      fsType = "btrfs";
      options = [ "subvol=home"  "compress=zstd"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a0da699c-99b7-4ea5-8757-35e1ca611c2d";
      fsType = "btrfs";
      options = [ "subvol=nix"  "compress=zstd" "noatime" ];
    };

  fileSystems."/models" =
    { device = "/dev/disk/by-uuid/a0da699c-99b7-4ea5-8757-35e1ca611c2d";
      fsType = "btrfs";
      options = [ "subvol=models"  "compress=zstd"];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
