[
  "float, class:^(org.kde.polkit-kde-authentication-agent-1)$"
  "float, class:^(Steam)$ title:^(Friends List)$"
  "size 500 500, class:^(Steam)$ title:^(Friends List)$"
  "float, class:^(steam)$ title:^(Friends List)$"
  "size 500 500, class:^(steam)$ title:^(Friends List)$"
  "size 930 495, class:^(firefox)$ title:^(Picture-in-Picture)$"
  "float, class:^(firefox)$ title:^(Picture-in-Picture)$"
  "suppressevent, fullscreen, class:^(firefox)$ title:^(Picture-in-Picture)$"
  "suppressevent, fullscreen, class:^(libreoffice-startcenter)$"
  "float, class:^(firefox)$, title:^(Firefox — Sharing Indicator)$"
  "suppressevent, fullscreen, class:^(firefox)$, title:^(Firefox — Sharing Indicator)$"
  "suppressevent, maximazie, class:^(firefox)$, title:^(Firefox — Sharing Indicator)$"
  "move 0 0, class:^(firefox)$, title:^(Firefox — Sharing Indicator)$"
  "suppressevent, fullscreen, class:^(firefox)$, title:^(Firefox — Sharing Indicator)$"
  "noinitialfocus, class:^(steam)$, title:^(notificationtoasts)"
  "float, class:^(com-atlauncher-App)$ title:^(ATLauncher Console)$"
  "opacity 0.9, class:^(WebCord)$"
  "float, class:^(org.keepassxc.KeePassXC)$ title: (Unlock)"
  "tile,class:^dev.warp.Warp.*$"
  "float, class:^(org.keepassxc.KeePassXC)$ title: (Passkey credentials)"
]
